# Generated by Django 4.2.11 on 2024-04-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_rename_user_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='package',
            name='image',
            field=models.ImageField(default=None, upload_to='gallery/'),
        ),
    ]
