# Generated by Django 4.2.11 on 2024-04-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_booking_status_alter_package_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.CharField(max_length=25),
        ),
    ]
